
/*Lista de palabras */
var listaPalabras = ["ALURA",
    "ORACLE",
    "CARTERA",
    "MUSICA",
    "COCODRILO",
    "TELEFONO",
    "ESGRIMA",
    "COMPUTADORA",
    "PARRILLA",
    "VACACIONES",
    "AMERICA",
    "ELECTRICIDAD",
    "COMPETICION",
    "GUITARRA",
    "BATERIA",
    "PALINDROMO",
    "ESTATUA",
    "MARADONA",
    "PERDIDA",
    "TELEVISOR",
    "PLASTICOLA",
    "ZAPATILLA",
    "JOROBA",
    "ALCOHOL",
    "CARACOL",
    "ARGENTINA",
    "CELULAR"];